import {
    CANCEL_BUTTON_ID,
    COLOR_INPUT_ID,
    DESC_INPUT_ID,
    DIALOG_BACKDROP_ID,
    DIALOG_ID,
    DIALOG_PANEL_BASIC_ID,
    DIALOG_PANEL_IMAGE_ID,
    DIALOG_TAB_BASIC_ID,
    DIALOG_TAB_IMAGE_ID,
    DIALOG_TITLE_ID,
    MAP_IMAGE_CLEAR_BUTTON_ID,
    MAP_IMAGE_CURRENT_ID,
    MAP_IMAGE_FILE_INPUT_ID,
    MAP_IMAGE_PICK_BUTTON_ID,
    MAP_IMAGE_SAVE_BUTTON_ID,
    NAME_INPUT_ID,
    PROGRESS_BAR_FILL_ID,
    PROGRESS_RANGE_ID,
    PROGRESS_VALUE_ID,
    SAVE_BUTTON_ID,
    STAGE_IMAGE_CLEAR_BUTTON_ID,
    STAGE_IMAGE_CURRENT_ID,
    STAGE_IMAGE_FILE_INPUT_ID,
    STAGE_IMAGE_PICK_BUTTON_ID,
    STAGE_IMAGE_SAVE_BUTTON_ID,
} from "./constants";

export function getStageDialogElements() {
  // ダイアログに必要なDOM参照をまとめて取得する。
  return {
    dialog: document.getElementById(DIALOG_ID),
    backdrop: document.getElementById(DIALOG_BACKDROP_ID),
    title: document.getElementById(DIALOG_TITLE_ID),
    tabBasic: document.getElementById(DIALOG_TAB_BASIC_ID),
    tabImage: document.getElementById(DIALOG_TAB_IMAGE_ID),
    panelBasic: document.getElementById(DIALOG_PANEL_BASIC_ID),
    panelImage: document.getElementById(DIALOG_PANEL_IMAGE_ID),
    progressRange: document.getElementById(PROGRESS_RANGE_ID),
    progressBarFill: document.getElementById(PROGRESS_BAR_FILL_ID),
    progressValue: document.getElementById(PROGRESS_VALUE_ID),
    nameInput: document.getElementById(NAME_INPUT_ID),
    descInput: document.getElementById(DESC_INPUT_ID),
    colorInput: document.getElementById(COLOR_INPUT_ID),
    stageImageFileInput: document.getElementById(STAGE_IMAGE_FILE_INPUT_ID),
    stageImagePickButton: document.getElementById(STAGE_IMAGE_PICK_BUTTON_ID),
    stageImageClearButton: document.getElementById(STAGE_IMAGE_CLEAR_BUTTON_ID),
    stageImageSaveButton: document.getElementById(STAGE_IMAGE_SAVE_BUTTON_ID),
    stageImageCurrent: document.getElementById(STAGE_IMAGE_CURRENT_ID),
    mapImageFileInput: document.getElementById(MAP_IMAGE_FILE_INPUT_ID),
    mapImagePickButton: document.getElementById(MAP_IMAGE_PICK_BUTTON_ID),
    mapImageClearButton: document.getElementById(MAP_IMAGE_CLEAR_BUTTON_ID),
    mapImageSaveButton: document.getElementById(MAP_IMAGE_SAVE_BUTTON_ID),
    mapImageCurrent: document.getElementById(MAP_IMAGE_CURRENT_ID),
    cancelButton: document.getElementById(CANCEL_BUTTON_ID),
    saveButton: document.getElementById(SAVE_BUTTON_ID),
  };
}
